// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-R24wsznr-T6v-q59g3WT95nBsb-laUI',
    appId: '1:884742160062:web:9f958310ab67e26da328ef',
    messagingSenderId: '884742160062',
    projectId: 'boulevared',
    authDomain: 'boulevared.firebaseapp.com',
    storageBucket: 'boulevared.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4SCBYHuHbP_POIR5WcjawR7pJGbOolgU',
    appId: '1:884742160062:android:e194f63b2dcb9ccaa328ef',
    messagingSenderId: '884742160062',
    projectId: 'boulevared',
    storageBucket: 'boulevared.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKwfdG6pXdQ0uffJilLMR2Gvs8s6oXnVQ',
    appId: '1:884742160062:ios:bc4ecd7b1393416da328ef',
    messagingSenderId: '884742160062',
    projectId: 'boulevared',
    storageBucket: 'boulevared.appspot.com',
    iosBundleId: 'com.example.realEstateMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKwfdG6pXdQ0uffJilLMR2Gvs8s6oXnVQ',
    appId: '1:884742160062:ios:bc4ecd7b1393416da328ef',
    messagingSenderId: '884742160062',
    projectId: 'boulevared',
    storageBucket: 'boulevared.appspot.com',
    iosBundleId: 'com.example.realEstateMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-R24wsznr-T6v-q59g3WT95nBsb-laUI',
    appId: '1:884742160062:web:4d40bfc741387193a328ef',
    messagingSenderId: '884742160062',
    projectId: 'boulevared',
    authDomain: 'boulevared.firebaseapp.com',
    storageBucket: 'boulevared.appspot.com',
  );
}
